name: ip_geolocation_api
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/NestorDevs

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  http: ^0.13.4
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
